# Generated by Django 4.2.1 on 2025-05-24 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
        ),
        migrations.CreateModel(
            name='HeightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Рост')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
        ),
        migrations.CreateModel(
            name='WeightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('gender', models.IntegerField(choices=[(1, 'Мужчина'), (2, 'Женщина')], verbose_name='Пол')),
                ('target_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Целевой вес')),
                ('goal', models.IntegerField(choices=[(1, 'Похудение'), (2, 'Тонус'), (3, 'Набор массы'), (4, 'Сушка')], verbose_name='Цель')),
                ('activity_level', models.IntegerField(choices=[(1, 'Сидячий'), (2, 'Легкая активность'), (3, 'Умеренная активность'), (4, 'Высокая активность')], verbose_name='Уровень активности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('cycle_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Цикл', to='users.cyclemodel', verbose_name='Цикл')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('height', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Рост', to='users.heightmodel', verbose_name='Рост')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('weight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Вес', to='users.weightmodel', verbose_name='Вес')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
