# Generated by Django 4.2.1 on 2025-05-26 00:29

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='heightmodel',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Рост', to='users.heightmodel', verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Вес', to='users.weightmodel', verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='weightmodel',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вес'),
        ),
    ]
