# Generated by Django 4.2.1 on 2025-06-04 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_heightmodel_user_weightmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cycle_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Цикл', to='users.cyclemodel', verbose_name='Цикл'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Рост', to='users.heightmodel', verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Вес', to='users.weightmodel', verbose_name='Вес'),
        ),
    ]
