# Generated by Django 4.2.1 on 2025-06-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_cycle_record_alter_user_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity_level',
            field=models.IntegerField(choices=[(1, 'Сидячий'), (2, 'Легкая активность'), (3, 'Умеренная активность'), (4, 'Высокая активность'), (5, 'Очень высокая активность')], verbose_name='Уровень активности'),
        ),
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.IntegerField(choices=[(1, 'Похудение'), (3, 'Набор массы'), (2, 'Тонус')], verbose_name='Цель'),
        ),
    ]
