# Generated by Django 4.2.1 on 2025-06-06 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_activity_level_alter_user_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mail',
            new_name='email',
        ),
        migrations.AddField(
            model_name='cyclemodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.IntegerField(choices=[(1, 'Похудение'), (2, 'Набор массы'), (3, 'Тонус')], verbose_name='Цель'),
        ),
    ]
