# Generated by Django 4.2.1 on 2025-06-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_mail_user_email_cyclemodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cycle_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='День текущего цикла'),
        ),
        migrations.AddField(
            model_name='user',
            name='cycle_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина цикла в днях'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_period_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней менструации'),
        ),
    ]
