# Generated by Django 4.2.1 on 2025-06-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_allergen_user_allergens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
