# Generated by Django 4.2.1 on 2025-06-08 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_bfp_user_bmi_user_cycle_record_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added'),
        ),
        migrations.AlterField(
            model_name='heightmodel',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='heightmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Changed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activity_level',
            field=models.IntegerField(choices=[(1, 'Sedentary'), (2, 'Light'), (3, 'Moderate'), (4, 'Hight'), (5, 'Extreme')], verbose_name='Activity level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bfp',
            field=models.FloatField(blank=True, null=True, verbose_name='Body Fat Percentage'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bmi',
            field=models.FloatField(blank=True, null=True, verbose_name='Body mass index'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cycle_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Current cycle day'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cycle_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cycle length in days'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cycle_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cycle', to='users.cyclemodel', verbose_name='Cycle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.IntegerField(choices=[(1, 'Weight loss'), (2, 'Weight gain'), (3, 'Maintenance')], verbose_name='Goal'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Height', to='users.heightmodel', verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_period_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last period date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='target_weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Target weight'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Changed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Weight', to='users.weightmodel', verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='weightmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Changed'),
        ),
        migrations.AlterField(
            model_name='weightmodel',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight'),
        ),
    ]
