# Generated by Django 4.2.1 on 2025-06-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_cyclemodel_created_at_alter_heightmodel_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cycle_record',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
