# Generated by Django 4.2.1 on 2025-06-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_cycle_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cycle_record',
            new_name='menstrual_phase',
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
    ]
