version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - fitness_network

  # Django Web Application
  web:
    build: .
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=0
    ports:
      - "8003:8003"
      - "8004:8004"
    restart: always
    networks:
      - fitness_network

  # Nginx for serving static files and as reverse proxy
  nginx:
    image: nginx:1.21
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - media_volume:/media
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always
    networks:
      - fitness_network

networks:
  fitness_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
