# Generated by Django 4.2.1 on 2025-05-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('importance', models.FloatField(default=0.0, help_text='Feature importance score (0-1)')),
            ],
            options={
                'ordering': ['-importance'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('last_updated', models.DateField()),
                ('accuracy', models.FloatField(help_text='Overall model accuracy (0-1)')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Model metadata',
            },
        ),
    ]
